// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// numeric_to_factor_cpp
CharacterVector numeric_to_factor_cpp(NumericVector num, CharacterVector levs, bool na_to_missing);
RcppExport SEXP syberiaMungebits2_numeric_to_factor_cpp(SEXP numSEXP, SEXP levsSEXP, SEXP na_to_missingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type num(numSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type levs(levsSEXP);
    Rcpp::traits::input_parameter< bool >::type na_to_missing(na_to_missingSEXP);
    rcpp_result_gen = Rcpp::wrap(numeric_to_factor_cpp(num, levs, na_to_missing));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP syberiaMungebits2_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
