# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

numeric_to_factor_cpp <- function(num, levs, na_to_missing = TRUE) {
    .Call('syberiaMungebits2_numeric_to_factor_cpp', PACKAGE = 'syberiaMungebits2', num, levs, na_to_missing)
}

rcpp_hello_world <- function() {
    .Call('syberiaMungebits2_rcpp_hello_world', PACKAGE = 'syberiaMungebits2')
}

